### ISSUE TITLE
attachment foreign key

### ISSUE THREAD

**Issue by asidirop** [BscThesis/aboard.iee.ihu.gr#1]
The announcement_id in  attachments table should be converted to BIGINT (20) UNSIGNED, so a foreign key could be added.

ALTER TABLE `aboard`.`attachments`
  CHANGE `announcement_id` `announcement_id` BIGINT (20) UNSIGNED NOT NULL, ADD FOREIGN KEY (`announcement_id`) REFERENCES `aboard`.`announcements` (`id`) ON UPDATE CASCADE ON DELETE CASCADE;

**Comment by nickcn** [comment]
Did you run this already against our DB and we just need the migration or shall I add the migration and then run it?

**Comment by nickcn** [comment]
Please check the contents of the file under: database/migrations/2020_08_26_005104_add_foreign_key_to_announcements_table.php.
Is this what we are looking for?
