### ISSUE TITLE
Event tags

### ISSUE THREAD

**Issue by nickcn** [BscThesis/aboard.iee.ihu.gr#14]
Old announcements with "Εκδηλώσεις" as their tag should also have `is_event` set to `true`.
Shall we do it directly in the DB or will you import again? @asidirop

**Comment by nickcn** [comment]
Actually it was easier than I thought.
`update announcements set is_event=1 where announcements.id in(select announcement_id from announcement_tag where tag_id=22 );`

**Comment by asidirop** [comment]
It is easy but there is no meaning doing it.
The idea is that the "is_event" announcements have a date-time attribute.
In old announcements, we cannot extract this information.
So they can just exist.



Antonis Sidiropoulos <https://www.it.teithe.gr/~asidirop/>, Assistant
Professor
Information Management & Software Engineering Laboratory
<http://imselab.it.teithe.gr>
Department of Information and Electronic Engineering
<https://www.iee.ihu.gr/> - International Hellenic University
<https://www.ihu.gr/>.
***@***.***, ***@***.***, ***@***.***,
***@***.***, ***@***.***
LinkedIn <http://www.linkedin.com/pub/antonis-sidiropoulos/a/32/8b3>,
researchgate
<http://www.researchgate.net/profile/Antonis_Sidiropoulos/?ev=hdr_xprf>,
academia <https://teithe.academia.edu/AntonisSidiropoulos>,  google scholar
<http://scholar.google.gr/citations?user=42WdccQAAAAJ&hl=el>, dblp
<http://dblp.org/pers/hd/s/Sidiropoulos:Antonis>, aminer
<https://aminer.org/profile/antonis-sidiropoulos/53f453e3dabfaee2a1d6a4f7>
