### ISSUE TITLE
Android api issue

### ISSUE THREAD

**Issue by ckatsanis** [BscThesis/aboard.iee.ihu.gr#25]
Problem when download file via android app through api with respond "Server Error"

**Comment by fkoustoulas** [comment]
It seems to be fixed. Thanks for mentioning it

**Comment by ckatsanis** [comment]
The problem still exists

**Comment by fkoustoulas** [comment]
yes it seems that it was a security issue. can you try again and test if issue is resolved?

**Comment by ckatsanis** [comment]
It works.
