### ISSUE TITLE
Refresh Tokens

### ISSUE THREAD

**Issue by asidirop** [BscThesis/aboard.iee.ihu.gr#6]
We must give the ability to an application to issue refresh tokens. 
This is a quite big addition.

**Comment by nickcn** [comment]
This will need some testing :)

**Comment by nickcn** [comment]
Backend implemented.
Frontend not yet. It's borked. :)

**Comment by nickcn** [comment]
@asidirop , please check the front end. It is fixed.
Access token lifetime is 1 minute for better error checking.

**Comment by nickcn** [comment]
Tokens expire in 120 minutes.
Refresh tokens expire in 1 week.
