### ISSUE TITLE
Tag selector

### ISSUE THREAD

**Issue by asidirop** [BscThesis/aboard.iee.ihu.gr#7]
Tag selector in new/edit announcement should be improved.
Here is a code example:

```
<html>
<head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
$(function prepareList() {
	$('#expList').find('li:has(ul)').children('a').click(function(event) {
		$(this).parent().children('ul').toggle('medium');
		return false;
	});
	$('#expList').find('li').children('ul').hide('medium');
});
</script>
<style>
#sel {max-height:10em; height:10em; overflow: auto; border: 1px solid black; width:30em;}
#sel ul {
  list-style-type: none;
  padding-left: 1em;
  }
</style>
</head>
<body>
<div id='sel'>
<ul  id="expList">
      <li class="intranet-folder"><input type='checkbox' name='aaa'/><a href='#'>1o etos</a>
        <ul>
          <li class="intranet-folder"><input type='checkbox'><a href='#'>January</a>
            <ul>
              <li><input type='checkbox'/><a href='#'>qwqwqw</a></li>
            </ul>
          </li>
          <li class="intranet-folder"><input type='checkbox'/><a href='#'>February</a>

            <ul>
              <li><input type='checkbox'/><a href='#'>asaasd</a>
</li>
            </ul>
          </li>
        </ul>
      </li>
      <li class="intranet-folder"><input type='checkbox'/><a href='#'>2o etos</a>

        <ul>
          <li class="intranet-folder"><input type='checkbox'/><a href='#'>November</a>

            <ul>
              <li><input type='checkbox'/><a href='#'>lalala</a>
</li>
            </ul>
          </li>
        </ul>
      </li>
<li class="intranet-folder"><input type='checkbox'/><a href='#'>Grammateia</a>
        <ul>
          <li class="intranet-folder"><input type='checkbox'/><a href='#'>November</a>

            <ul>
              <li><input type='checkbox'/>lalala</li>
            </ul>
          </li>
        </ul>
      </li>
<li class="intranet-folder"><input type='checkbox'/><a href='#'>Lala</a>
        <ul>
          <li class="intranet-folder"><input type='checkbox'/><a href='#'>November</a>
            <ul>
              <li><input type='checkbox'/>lalala</li>
            </ul>
          </li>
        </ul>
      </li>
    </ul>
    <div>
```

**Comment by nickcn** [comment]
So we need to have the tags in a tree view?

**Comment by asidirop** [comment]
Yes.

Also, a filtering procedure should be useful, but this is the next step.

Antonis Sidiropoulos <https://www.it.teithe.gr/~asidirop/>, Assistant
Professor
Information Management & Software Engineering Laboratory
<http://imselab.it.teithe.gr>
Department of Information and Electronic Engineering
<https://www.iee.ihu.gr/> - International Hellenic University
<https://www.ihu.gr/>.
***@***.***, ***@***.***, ***@***.***,
***@***.***, ***@***.***
LinkedIn <http://www.linkedin.com/pub/antonis-sidiropoulos/a/32/8b3>,
researchgate
<http://www.researchgate.net/profile/Antonis_Sidiropoulos/?ev=hdr_xprf>,
academia <https://teithe.academia.edu/AntonisSidiropoulos>,  google scholar
<http://scholar.google.gr/citations?user=42WdccQAAAAJ&hl=el>, dblp
<http://dblp.org/pers/hd/s/Sidiropoulos:Antonis>, aminer
<https://aminer.org/profile/antonis-sidiropoulos/53f453e3dabfaee2a1d6a4f7>

**Comment by nickcn** [comment]
Filterning how? So I can start thinking of the ways.

**Comment by asidirop** [comment]
It's easy. Two lines with jquery.
The same philosophy as the tree expand.

Antonis Sidiropoulos <https://www.it.teithe.gr/~asidirop/>, Assistant
Professor
Information Management & Software Engineering Laboratory
<http://imselab.it.teithe.gr>
Department of Information and Electronic Engineering
<https://www.iee.ihu.gr/> - International Hellenic University
<https://www.ihu.gr/>.
***@***.***, ***@***.***, ***@***.***,
***@***.***, ***@***.***
LinkedIn <http://www.linkedin.com/pub/antonis-sidiropoulos/a/32/8b3>,
researchgate
<http://www.researchgate.net/profile/Antonis_Sidiropoulos/?ev=hdr_xprf>,
academia <https://teithe.academia.edu/AntonisSidiropoulos>,  google scholar
<http://scholar.google.gr/citations?user=42WdccQAAAAJ&hl=el>, dblp
<http://dblp.org/pers/hd/s/Sidiropoulos:Antonis>, aminer
<https://aminer.org/profile/antonis-sidiropoulos/53f453e3dabfaee2a1d6a4f7>

**Comment by nickcn** [comment]
I have added the same component that we use in user preferences for now.
It will need a little more work.

**Comment by asidirop** [comment]
closed
