### ISSUE TITLE
testbed.aboard.iee.ihu.gr

### ISSUE THREAD

**Issue by nickcn** [BscThesis/aboard.iee.ihu.gr#8]
It would be nice if we had a staging domain for tests.

**Comment by asidirop** [comment]
Δεν μπορούμε να το κάνουμε στο aboard.iee.ihu.gr/test/ ?
To nginx δεν έχει κάτι σαν το Alias του apache
ώστε να κάνουμε
Alias /test/     /home/aboard/tboard..../public
???


Antonis Sidiropoulos <https://www.it.teithe.gr/~asidirop/>, Assistant
Professor
Information Management & Software Engineering Laboratory
<http://imselab.it.teithe.gr>
Department of Information and Electronic Engineering
<https://www.iee.ihu.gr/> - International Hellenic University
<https://www.ihu.gr/>.
***@***.***, ***@***.***, ***@***.***,
***@***.***, ***@***.***
LinkedIn <http://www.linkedin.com/pub/antonis-sidiropoulos/a/32/8b3>,
researchgate
<http://www.researchgate.net/profile/Antonis_Sidiropoulos/?ev=hdr_xprf>,
academia <https://teithe.academia.edu/AntonisSidiropoulos>,  google scholar
<http://scholar.google.gr/citations?user=42WdccQAAAAJ&hl=el>, dblp
<http://dblp.org/pers/hd/s/Sidiropoulos:Antonis>, aminer
<https://aminer.org/profile/antonis-sidiropoulos/53f453e3dabfaee2a1d6a4f7>

**Comment by nickcn** [comment]
It _might_ be a little problematic with Laravel. I will research.
