### ISSUE TITLE
English + greek names

### ISSUE THREAD

**Issue by nickcn** [BscThesis/aboard.iee.ihu.gr#9]
Have both english and greek names for users in DB

**Comment by nickcn** [comment]
@asidirop , what is the search attribute for the names?
Now we use `cn`, which must be for the english name.

**Comment by asidirop** [comment]
Υπάρχουν τα cn και τα displayName
[cn;lang-el] => Αντώνης Σιδηρόπουλος
[cn] => Antonis Sidiropoulos
[displayName;lang-el] => Αντώνης Σιδηρόπουλος
[displayName] => Antonis Sidiropoulos
νομίζω καλύτερα τα displayName γιατί είναι από το public profile του χρήστη.

Antonis Sidiropoulos <https://www.it.teithe.gr/~asidirop/>, Assistant
Professor
Information Management & Software Engineering Laboratory
<http://imselab.it.teithe.gr>
Department of Information and Electronic Engineering
<https://www.iee.ihu.gr/> - International Hellenic University
<https://www.ihu.gr/>.
***@***.***, ***@***.***, ***@***.***,
***@***.***, ***@***.***
LinkedIn <http://www.linkedin.com/pub/antonis-sidiropoulos/a/32/8b3>,
researchgate
<http://www.researchgate.net/profile/Antonis_Sidiropoulos/?ev=hdr_xprf>,
academia <https://teithe.academia.edu/AntonisSidiropoulos>,  google scholar
<http://scholar.google.gr/citations?user=42WdccQAAAAJ&hl=el>, dblp
<http://dblp.org/pers/hd/s/Sidiropoulos:Antonis>, aminer
<https://aminer.org/profile/antonis-sidiropoulos/53f453e3dabfaee2a1d6a4f7>

**Comment by nickcn** [comment]
displayName does not work. I have used cn and it's ok. If you need me to change it, please let me know.

**Comment by asidirop** [comment]
It should work.

But it OK with the cn and cn;lang-el

[image: image.png]
![image](https://user-images.githubusercontent.com/1404892/115588900-e8109000-a2d7-11eb-9860-18f9091160a5.png)
